#!/bin/bash

ssm_username=$1
ssm_password=$2
local_port=${3:-54000}
remote_port=${4:-3389}
ssm_host=${5:-localhost}

mstsc_exists="$(which mstsc.exe)"
cmdkey_exists="$(which cmdkey.exe)"

# only proceed if we have Windows binaries available
if [ -z "$mstsc_exists" ] || [ -z "$cmdkey_exists" ]
then
  exit 0
fi

echo "Waiting for the local RDP port to become available..."

# wait for the local port to be available
while ! nc -z $ssm_host $local_port; do   
  sleep 1
done

echo "Starting the RDP connection..."

# save the generated credentials
cmdkey.exe /generic:"$ssm_host" /user:"$ssm_username" /pass:"$ssm_password"

# launch the RDP client, sleep for a bit to allow time for the tunnel to establish
mstsc.exe /v:"$ssm_host:$local_port"

# remove the credentials as well
cmdkey.exe /delete:"$ssm_host"
