#!/bin/bash

if [ $# -eq 0 ]
then
  echo "Syntax:"
  echo "  ssm-session <options> <args>"
  echo "    Options:"
  echo "      -n (optional): AWS instance tag name"
  echo "      -i (optional): AWS instance ID"
  echo "      Either -n or -i must be specified"
  exit 0
fi

INSTANCE_NAME=""
INSTANCE_ID=""

while getopts "n:i:" opt; do
  case ${opt} in
    n) INSTANCE_NAME=${OPTARG};;
    i) INSTANCE_ID=${OPTARG};;
  esac
done

if [ -z $INSTANCE_NAME ] && [ -z $INSTANCE_ID ]
then
  echo "Must pass instance name with -n or instance id with -i"
  exit 2
fi

shift $((OPTIND -1))

if [ -z $INSTANCE_ID ]
  then
  # find the instance ID based on Tag Name
  INSTANCE_ID=$(aws-resolve-host $INSTANCE_NAME)

  exit_code=$?

  if [ $exit_code -eq 1 ]
  then
    echo "Unable to resolve AWS host by tag name: $INSTANCE_NAME"
    exit $exit_code
  fi
fi

# create the session
aws ssm start-session --target $INSTANCE_ID
