#!/bin/bash

instance_name=$1
remote_port=$2
local_port=$3

# find the instance ID based on Tag Name
INSTANCE_ID=$(aws-resolve-host $instance_name)

# create the port forwarding tunnel
aws ssm start-session --target $INSTANCE_ID \
                      --document-name AWS-StartPortForwardingSession \
                      --parameters "{\"portNumber\":[\"$remote_port\"],\"localPortNumber\":[\"$local_port\"]}"
